export const BUTTON_COLORS = {
  BACKGROUND_INACTIVE: '#FFFFFF',
  BACKGROUND_ACTIVE: '#F0F0F0',
  SYMBOL_INACTIVE: '#949CA2',
  SYMBOL_ACTIVE: '#414F58',
  TOOLTIP_BACKGROUND: '#FFFFFF',
  TOOLTIP: '#000000',
};

export const POPUP_STYLE = {
  borderRadius: '5px',
  backgroundColor: BUTTON_COLORS.TOOLTIP_BACKGROUND,
  color: BUTTON_COLORS.TOOLTIP,
};
